version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"           
    schedule:
      interval: "monthly"    # Check for updates once a month
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"